### ISSUE TITLE
find typos

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/DesignThinking-LeanStartup#1]
maybe design
<img width="311" alt="image" src="https://user-images.githubusercontent.com/37795442/168757684-b954f987-68f2-40fb-87b4-44edd75ec426.png">

**Comment by will-ww** [comment]
> maybe design <img alt="image" width="311" src="https://user-images.githubusercontent.com/37795442/168757684-b954f987-68f2-40fb-87b4-44edd75ec426.png">

这种还可以提个PR，算个贡献~ :-)
