### ISSUE TITLE
关于作业报告的问题

### ISSUE THREAD

**Issue by GuoTeng-ECNU** [X-lab2017/DesignThinking-LeanStartup#10]
请问报告里需要粘贴上实验材料的文字说明吗

**Comment by zhicheng-ning** [comment]
> 请问报告里需要粘贴上实验材料的文字说明吗

按照自己的实践过程，用自己的话讲清楚就可以，如果能发现实验步骤或者内容有任何错误，欢迎提 Issue 或者联系助教！

**Comment by GuoTeng-ECNU** [comment]
> > 请问报告里需要粘贴上实验材料的文字说明吗
> 
> 按照自己的实践过程，用自己的话讲清楚就可以，如果能发现实验步骤或者内容有任何错误，欢迎提 Issue 或者联系助教！

有格式要求吗

**Comment by zhicheng-ning** [comment]
格式就是按照每个实验自己的格式【实验目的】【实验环境】【实验步骤】......，只要考虑目录层级就好了，字体什么的格式没有硬性规定

**Comment by tyn1998** [comment]
该issue的讨论内容已经摘抄到 #8 中，于是先关闭该issue。

感谢 @GuoTeng-ECNU 同学的提问~
