### ISSUE TITLE
【问题】实验8.1.4问题

### ISSUE THREAD

**Issue by GuoTeng-ECNU** [X-lab2017/DesignThinking-LeanStartup#12]
centos7安装docker的命令应为curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun，而不是curl -fsSL https://get.docker.com " bash -s docker --mirror Aliyun

**Comment by GuoTeng-ECNU** [comment]
下面的curl -sSL https://get.daocloud.io/docker " sh之类的也需要将"换为|

**Comment by tyn1998** [comment]
使用反引号\`xxx\`包裹行内代码阅读效果更佳哦~

还可以使用

\`\`\`bash
xxx
\`\`\`

来包裹块代码，效果如下：

```bash
curl -fsSL https://get.docker.com/ | bash -s docker --mirror Aliyun
```
