### ISSUE TITLE
[创意项目] 一起做一个数据学院课程笔记共创的项目

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/DesignThinking-LeanStartup#13]
- 选定一门或多门课程，例如：数据科学与工程算法
- 用设计思维的套路做：用户调研（周围同学、师弟师妹）
- 怎样做
- 用什么工具
- 最终原型是什么：Web应用或者仓库

Any suggestion~

**Comment by will-ww** [comment]
举手报名~

**Comment by tyn1998** [comment]
补充信息：

很多开源项目的文档也是开源项目，举个例子，[Echarts的hand-book](https://echarts.apache.org/handbook/zh/get-started/)：

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/32434520/177899331-2e4c4d70-afb1-4021-b73a-0fe1f050078f.png">

其实就是套了个博客框架的markdown文件的协作。本项目旨在让同学们通过类似的方式来打造数据学院的课程笔记，集全院智慧于一部，永久更新，代代相传~

参考：

- https://www.gitbook.com/
- https://github.com/Anduin2017/HowToCook
- https://github.com/tyn1998/tyn1998.github.io

**Comment by shiiiyuiuxjni** [comment]
![协作笔记](https://user-images.githubusercontent.com/108856725/180353513-6da1813e-6822-4f19-8475-e7a989dbac29.jpg)
