### ISSUE TITLE
[创意项目]  X-lab 开源治理可视化大屏

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/DesignThinking-LeanStartup#14]
有感兴趣的一起一起~

http://dashboard-overview.opensource-service.com/?label=xlab

在此基础，有针对性地根据 X-lab 开源项目与贡献者信息，进行系统展示~

**Comment by tyn1998** [comment]
> 在此基础，有针对性地根据 X-lab 开源项目与贡献者信息，进行系统展示~

本助教帮同学们理解一下~

此创意项目要求：

- 在[已有组织级别的视图](http://dashboard-overview.opensource-service.com/?label=xlab)上
  - 新增一个组件用于展示组织成员每月openrank（即影响力）情况

- 在[已有仓库级别的视图](http://repo-data.opensource-service.cn/?r=X-lab2017/open-digger&)中，新增一个组件用于呈现：
  - 仓库中所有X-lab成员在本仓库中的openrank

数据来源在该项目被选择后再沟通，此处应该要 @frank-zsy 学长 :)

相关资料：

- DataV是什么：https://help.aliyun.com/product/43570.html

**Comment by xudingsheng** [comment]
许定胜，徐啟航

**Comment by will-ww** [comment]
这个项目，我可以来一起帮忙指导与优化~

**Comment by xudingsheng** [comment]
visual screen

**Comment by JasonXQH** [comment]
@frank-zsy  学长好，请问这个大屏的编辑权限可以给我们一下吗，还有大屏的更新数据，我们能拿得到吗？谢谢~

**Comment by tyn1998** [comment]
刚刚看了最新的大屏，我发现组织视图下活跃度榜单中的行是可以点击的，点击进入到对应的repo视图，于是修改了[上面comment](https://github.com/X-lab2017/DesignThinking-LeanStartup/issues/14#issuecomment-1178433970)中的要求。

我也来问几个问题：

1. 我注意到 @frank-zsy 学长在两个级别的视图中都没有给出开发者影响力的排行，这是有意为之吗？如果是的话，项目要求还得改，因为目前要求是做这方面的内容的。
2. openrank是不是就是影响力？
3. DataV可以clone一个看板吗，或者是编辑的时候可以创建分支吗，这是考虑需要给学弟们一个安全的操作空间 🤣 
4. 大屏的数据源都存在oss中吗？我用开发者调试工具看network没找到相关json文件请求

**Comment by frank-zsy** [comment]
> 刚刚看了最新的大屏，我发现组织视图下活跃度榜单中的行是可以点击的，点击进入到对应的repo视图，于是修改了[上面comment](https://github.com/X-lab2017/DesignThinking-LeanStartup/issues/14#issuecomment-1178433970)中的要求。
> 
> 我也来问几个问题：
> 

1. 影响力本身是一个计算成本较高的指标，目前全域项目影响力在 Hypercrx 使用的数据中是存在的，可以直接从 OSS 上调用。
2. OpenRank 就是影响力。
3. 我可以复制一份到实验室账号，目前这个大屏是在我个人云账号下的。
4. 使用的是 OSS 的数据，但由于 DataV 的动态能力不强，所以其实是在访问一个后端服务，这个后端服务会把 OSS 的数据返回到前端。

目前比较麻烦的是，对于单项目内部每个开发者的  OpenRank 是一个计算成本很高的指标，目前仅有要用于分配的几个项目才会进行计算，其他项目是没有的。这部分数据也没有开放出来，需要的话可以导出到 OSS 中。

**Comment by JasonXQH** [comment]
> 

嗯嗯，麻烦学长复制好以后留个项目地址，OSS是放在哪个云上的，我们有权限查看吗，有的话我也想看一下~

**Comment by tyn1998** [comment]
感谢 @frank-zsy 的回答！

所以接下来这个项目应该是这么来做的：

1. 等待Frank学长复制一份到实验室账号，然后通过合适的权限机制将实验室的克隆版本交给该小组
2. 项目的影响力获取参考这样的URL：https://oss.x-lab.info/hypercrx_repo/microsoft/vscode.json
（但是应该用不上，因为项目级别的影响力已经集成在现有大屏里了）
3. 麻烦Frank学长本地跑出项目内的成员影响力数据
4. 之后就能开始干了！

**Comment by JasonXQH** [comment]
> 
谢谢学长帮我们理清思路，您提供的 这个notebook中也有openrank的相关数据，也可以作为可视化数据的一部分
https://github.com/X-lab2017/open-digger/blob/master/notebook/community_analysis/xlab.ipynb

**Comment by tyn1998** [comment]
> > 
> 
> 谢谢学长帮我们理清思路，您提供的 这个notebook中也有openrank的相关数据，也可以作为可视化数据的一部分 https://github.com/X-lab2017/open-digger/blob/master/notebook/community_analysis/xlab.ipynb

对的，这是我最开始想到的，但由于我对OpenDigger还不是很熟悉，我不清楚你们本地能不能直接跑出来。这里面的确包含了6、7、8月的xlab成员在xlab下的仓库中的openrank值。

**Comment by frank-zsy** [comment]
我会拷贝组织和仓库的两个大屏到实验室的 DataV 中，另外项目内的影响力数据我也会整理输出到 OSS 上，这样就可以直接集成了。

**Comment by frank-zsy** [comment]
总体治理大屏与单项目数据大屏都已拷贝到实验室空间中，大家可以随意修改，但数据源是没有拷贝的，大家需要重新配置一下

**Comment by tyn1998** [comment]
OK，我晚点问管理员要一个子账号，谢谢Frank！

**Comment by tyn1998** [comment]
感谢 @JingbenShi668 提供技术支持！

现在已经有一个可以操作Xlab阿里云账号下DataV产品的RAM用户了，我将私发给 @JasonXQH，除了涉及到的两个大屏，不要操作其他大屏哦。

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/32434520/188839799-0b0eb5f0-18b5-44e4-8409-a1d517bcc71d.png">

RAM用户要这么登录：

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/32434520/188839970-e10208f6-e26a-467b-a8d2-6519850c197d.png">

**Comment by JasonXQH** [comment]
> 

<img width="1491" alt="iShot_2022-09-08_22 57 34" src="https://user-images.githubusercontent.com/62499394/189155882-2cfdbaf7-e816-43a1-8cc3-d28f9b9c66bb.png">

**Comment by JasonXQH** [comment]
> 感谢 @JingbenShi668 提供技术支持！
> 
> 现在已经有一个可以操作Xlab阿里云账号下DataV产品的RAM用户了，我将私发给 @JasonXQH，除了涉及到的两个大屏，不要操作其他大屏哦。
> 
> <img alt="image" width="1164" src="https://user-images.githubusercontent.com/32434520/188839799-0b0eb5f0-18b5-44e4-8409-a1d517bcc71d.png">
> 
> RAM用户要这么登录：
> 
> <img alt="image" width="1172" src="https://user-images.githubusercontent.com/32434520/188839970-e10208f6-e26a-467b-a8d2-6519850c197d.png">

学长好，datav大屏昨天还有权限编辑，今天用账号密码登录就没有权限了，请问这是为啥呀

**Comment by tyn1998** [comment]
@JasonXQH 学弟，我这里刚刚测试登录编辑，是可以的，你再试试看？

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/32434520/189157499-4d3b6382-16a0-4f92-82b8-6510512a2eed.png">

**Comment by JasonXQH** [comment]
> @JasonXQH 学弟，我这里刚刚测试登录编辑，是可以的，你再试试看？
> 
> <img alt="image" width="1246" src="https://user-images.githubusercontent.com/32434520/189157499-4d3b6382-16a0-4f92-82b8-6510512a2eed.png">

收到，是我的问题，我可以了~谢谢

**Comment by JasonXQH** [comment]
> 项目内的影响力数据

@frank-zsy 学长好，请问有项目内的影响力数据的链接吗，我这边还需要一点数据~
