### ISSUE TITLE
【问题】实验8.3.3用户界面 实验 bug

### ISSUE THREAD

**Issue by JasonXQH** [X-lab2017/DesignThinking-LeanStartup#15]
指导书代码：driver = webdriver.Chrome(service=Service(path))
实际代码:driver = webdriver.Chrome('./chromedriver') 

selenium版本：3.141.0
chromedriver版本： 103.0.5060.53

**Comment by zhicheng-ning** [comment]
> 指导书代码：driver = webdriver.Chrome(service=Service(path))

实验中是有说明的 `源代码中的 path，需要修改为读者本地存放
ChromeDriver 的地址`。
```python
driver = webdriver.Chrome(service=Service(path)) #path 为 ChromeDriver 的本地路径
```
