### ISSUE TITLE
【建议】上周GitHub实践课在水杉上的课程序号和名称

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/DesignThinking-LeanStartup#16]
如图，目前显示为：

- LESSON 1 “Git基本操作”。

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/32434520/177066225-c29e808e-b830-462c-805c-82ca1d9b6d5a.png">

我认为这样更好：

- LESSON 4 “Git&GitHub协作开发实践课”

**Comment by zhicheng-ning** [comment]
@soobun 苏老师可以看一下~

**Comment by soobun** [comment]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/20661689/177085965-98ba1770-a2ad-4129-ba98-b541aadba4ce.png">

可以，那我就按该计划表来组织，如果有标题修改请随时告知。
