### ISSUE TITLE
[创意项目] 基于GitHub的游戏化作业或者习题练习平台

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/DesignThinking-LeanStartup#17]
项目详情如下

- https://github.com/OpenEduTech/.github/issues/2

**Comment by AliceCodeZhang** [comment]
作业要求： 原型+ 技术要点阐述

**Comment by Airthe911** [comment]
李嘉豪 徐俊希望认领，Explore code in the game

**Comment by Airthe911** [comment]
组名：Code Hunter

**Comment by Airthe911** [comment]
![项目海报](https://user-images.githubusercontent.com/90237696/180353782-4634fa14-9f15-491d-a62c-6bb14d0e9beb.jpg)
