### ISSUE TITLE
[创意项目] 开源参与度高校排行榜

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/DesignThinking-LeanStartup#18]
根据多个数据来源，以及参与的 GitHub 项目的活跃度/影响力等因素，开发一个基于 Web 的高校开源参与度排行榜，类似 https://open-leaderboard.x-lab.info/

具体内容可以参考：https://github.com/orgs/X-lab2017/discussions/117

**Comment by tyn1998** [comment]
此项目没有队伍选择，故暂时关闭。
