### ISSUE TITLE
[创意项目] 基于语雀工具的交互式课本

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/DesignThinking-LeanStartup#19]
语雀是一款开放的、功能强大的知识库管理工具，可以方便的将不同的知识单位组织在一起。

例如：https://xlab2017.yuque.com/msdpvs/me6vqg/bvytcd

可以选定一门感兴趣的课程，用语雀来组织该门课程的不同知识单位，成为一个新型的交互式课本。

可选课程包括：

- 数据科学与工程导论
- 算法可视化
- 开源软件通识基础
- 自由提出

**Comment by Bruce-Jay** [comment]
No access to the link: [https://xlab2017.yuque.com/msdpvs/me6vqg/bvytcd](url)
我没有用过语雀，但是对于这个项目比较感兴趣，可以把这个链接的权限设置为公开吗

**Comment by will-ww** [comment]
https://xlab2017.yuque.com/docs/share/67c44ebd-2aad-4658-a05b-d67cef31ec83?# 《💡新一代交互式“数字课本”》

看不到吗？

**Comment by Bruce-Jay** [comment]
> https://xlab2017.yuque.com/docs/share/67c44ebd-2aad-4658-a05b-d67cef31ec83?# 《💡新一代交互式“数字课本”》
> 
> 看不到吗？

感谢老师！现在可以看到了！

**Comment by Bruce-Jay** [comment]
林以任，郭腾，刘天扬已组队，名称ideabook

**Comment by will-ww** [comment]
强烈推荐 https://codepen.io/

算法类的话，有很多好的模块可以来选择~

**Comment by Neat12138** [comment]
项目海报
![基于语雀工具的交互式课本 ](https://user-images.githubusercontent.com/84450199/180353724-d73eca7c-784d-4df3-88c5-e0c9f74702b1.png)

**Comment by Bruce-Jay** [comment]
交互式课本，排序部分，已完成

**Comment by GuoTeng-ECNU** [comment]
交互式课本，BFS，DFS，已完成

**Comment by GuoTeng-ECNU** [comment]
交互式课本，贪心算法，已完成

**Comment by GuoTeng-ECNU** [comment]
交互式课本，分治算法，已完成

**Comment by GuoTeng-ECNU** [comment]
交互式课本，Kruskal算法，Dijkstra算法，已完成
