### ISSUE TITLE
【课前吐槽作业】吐槽一个你用得不好的产品，可以是实物类或者应用类

### ISSUE THREAD

**Issue by AliceCodeZhang** [X-lab2017/DesignThinking-LeanStartup#20]
让我们吐槽一个你觉得不好的产品，然后说说为什么不好

**Comment by Bruce-Jay** [comment]
百度。往大了看，有魏泽西事件；往小了看，百度不仅广告多，而且身边同学发生了一件真实事件，在百度上面搜“一个字是16位吗”结果第一页的答案答非所问——明朝有16位皇帝balahbalah，合理怀疑是因为他平时看历史的东西看多了然后导致了百度搜索引擎的类似于“过拟合”的现象
同时，在百度搜索结果经常定位至内容农场，基本前三个搜索结果中必有一个，在我尚未了解搜索引擎的时候深受其害。
百度的网盘先吸纳用户然后进行强制收费——基本上不充会员就不能正常下载；百度的输入法也会窃取用户的数据上传到云端（虽然国产的都是这样子）云云，这一点我认为是一个关乎隐私和便利的trade-off
总之，我认为百度系列的产品或者说应用，不能说全都是流氓，但是肯定是王莽谦恭未篡时
类似的思路可以类推至WPS, 360, 腾讯系等软件

**Comment by tyn1998** [comment]
<img width="149" alt="image" src="https://user-images.githubusercontent.com/32434520/177443412-a8a90376-aafe-4394-9190-8d3264e314f3.png">

海狸洗衣！此款app故意/无意使支付繁琐化，下单一次要花10秒。

**Comment by zhicheng-ning** [comment]
石墨文档！！！
以我的体验来看，当文档中内容很多时，石墨文档极其不稳定，经常出现延迟现象，除此之外，文档在加载过程中时不时会卡住，有时候还会莫名其妙的出现 Bug ，如「文档初始化异常，请稍后刷新重试」、「文档发生编辑错误，为防止丢失，请联系客服进行修复」，等等。

**Comment by Airthe911** [comment]
高校体育！我用过最烂的app之一，我立志修完体育课后立即卸载它。
如果说它充斥着广告，是因为它没有任何付费服务，需要靠广告费来维持运营，那高校体育极其不稳定的网络连接和用户体验性就很难找到借口了。打开高校体育app时经常会出现更新提醒，但有时按照要求完成软件更新后，再次打开app，仍然提示要更新，且要更新的版本就是刚刚已经更新过的版本，或是出现更新后app闪退等现象，严重影响使用；同时高校体育经常会出现网络异常，需要多次重启后才能正常使用；在使用高校体育跑步打卡时，也经常出现吞步数等问题，并且有着多种卡里程，卡配速的bug（之前看到某个同学当天跑步150km)。

**Comment by tyn1998** [comment]
上周已上课，故关闭此issue~
