### ISSUE TITLE
【项目汇总】4个创意项目与4支队伍，让我们拭目以待 🚀 

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/DesignThinking-LeanStartup#21]
# 项目分组信息

- #13 (@shiiiyuiuxjni) => Swindle
- #14 (@10195501406、@JasonXQH) => visual screen
- #17 (@Airthe911、@XuJun2002) => Code Hunter
- #19 (@Bruce-Jay、@GuoTeng-ECNU、@Neat12138) => ideabook

# 其他

请前往创意项目对应的issue讨论，此issue仅汇总信息。

**Comment by will-ww** [comment]
等组队好后，我们每个组会安排一位老师或助教，协助项目的开展~

**Comment by shiiiyuiuxjni** [comment]
我的队名叫Swindle

**Comment by zhicheng-ning** [comment]
> 等组队好后，我们每个组会安排一位老师或助教，协助项目的开展~

各项目对应的老师和助教安排如下~
- #13 @tyn1998 
- #14 @will-ww 
- #17 @AliceCodeZhang 
- #19 @zhicheng-ning

**Comment by zhicheng-ning** [comment]
课程圆满结束 🎉

**Comment by will-ww** [comment]
感谢大家的支持！
