### ISSUE TITLE
【无效地址】实验 8.1.7

### ISSUE THREAD

**Issue by Bruce-Jay** [X-lab2017/DesignThinking-LeanStartup#26]
![image](https://user-images.githubusercontent.com/90242019/181154032-5ae15059-5e71-4019-bab1-f4ba8742c9b6.png)
输入下图中的地址时，出现 404，应该是链接失效了
![image](https://user-images.githubusercontent.com/90242019/181154159-8f81c58f-cb0f-4218-b46b-fa15f43d23cf.png)

**Comment by zhicheng-ning** [comment]
是的，对于软件包，全部从源码仓库中排除出来了
