### ISSUE TITLE
【问题】 实验 8.3.3

### ISSUE THREAD

**Issue by Bruce-Jay** [X-lab2017/DesignThinking-LeanStartup#27]
步骤五在后端服务都启动的情况下，运行 test_login_unit.py 时，没有测试通过，不知为何
![6f5bf03d574fea96f5c9460aa053253](https://user-images.githubusercontent.com/90242019/182102243-320148b6-21cf-4f4e-841e-6a061675ffab.jpg)

**Comment by zhicheng-ning** [comment]
Hi，@Kx-Chen-99，有空看下~
实验 8.3.3 步骤五正常情况如下图

![image](https://user-images.githubusercontent.com/39022409/182103712-3df4aedf-e951-4df4-8a35-bb126e092789.png)

**Comment by Kx-Chen-99** [comment]
@Bruce-Jay 请问还有更详细的信息吗，从截图来看是没有执行任何测试的

**Comment by Bruce-Jay** [comment]
![image](https://user-images.githubusercontent.com/90242019/182106828-4f3b00cf-b584-48d2-97f3-a98e70a574db.png)
运行程序之后就一直停留在这个页面了，浏览器不会自动关闭

同时终端显示没有测试通过

**Comment by Kx-Chen-99** [comment]
程序正常运行，但打开浏览器显示空白页面，问题在于selenium没有成功打开前端页面。
1. 可以先检查一下前端页面是否能正常打开
2. 如果可以正常打开，再重新尝试运行该测试
3. 如果测试还是失败，可以尝试使用等待（举例如下）
```
driver.implicitly_wait(30) # 隐式等待30s
```
一般以上步骤即可解决，多运行几遍测试也可。实在不行可以重启前端、PyCharm、关闭浏览器后再进行尝试

**Comment by Bruce-Jay** [comment]
![image](https://user-images.githubusercontent.com/90242019/182135418-614a2131-eb61-4103-9784-0ddbfb064184.png)
前端页面可以正常打开，重新运行还是失败，昨天也失败了很多次

等待 30s 以上，浏览器仍未自动关闭

是否可能为电脑过于低配的原因？我的电脑在启动了六个服务之后，再启动 pycharm 进行测试就会很卡，是否与配置有关？

**Comment by Kx-Chen-99** [comment]
可以将隐式等待放在driver.get()前（图中第10行）试试。

如果能正常打开前端页面、运行测试时浏览器正常弹出，即可排除测试代码出现问题。
我没有遇见过多次运行仍然失败的情况，不能肯定是配置造成的影响。但页面加载过慢/Chrome响应过慢的确会导致该情况的发生。

另，chrome和webdriver的版本是否一致呢？

**Comment by Bruce-Jay** [comment]
刚刚已解决。感谢 @zhicheng-ning 的分享解决方法 https://www.jianshu.com/p/63f8905009df

测试已跑通

![54d086fda0744415638ee8fc0851f76](https://user-images.githubusercontent.com/90242019/182139565-d128ad96-8944-4a18-84ed-f3b8b185703c.jpg)

需要修改一下 test_login_unit 中的代码，测试方法以 test 开头

![f163d223b74994671393d5afcd943de](https://user-images.githubusercontent.com/90242019/182139676-e28a90e1-d2ac-4845-a6c6-e098b0e385c2.jpg)

**Comment by zhicheng-ning** [comment]
> 测试已跑通

图片左下角显示 `Tests Failed: 1`，这个是意料之中的吗？

**Comment by Bruce-Jay** [comment]
> > 测试已跑通
> 
> 图片左下角显示 `Tests Failed: 1`，这个是意料之中的吗？

![image](https://user-images.githubusercontent.com/90242019/182144363-60a839fb-b4f5-4b8d-ade9-ca657023055e.png)
重试已成功

以及，所使用的 junit 版本

![85e2cabadfb83c3d10b6204ccfebf4a](https://user-images.githubusercontent.com/90242019/182144465-bbde665c-125a-4f25-aa67-cb68cb9cc917.jpg)

**Comment by zhicheng-ning** [comment]
Thanks for @Kx-Chen-99 , @Bruce-Jay . This issue has been completed.
