### ISSUE TITLE
【问题】 实验 8.3.4

### ISSUE THREAD

**Issue by Bruce-Jay** [X-lab2017/DesignThinking-LeanStartup#28]
步骤三的测试一，参数应当在 params 中传入

测试二是否有问题？无法访问

![image](https://user-images.githubusercontent.com/90242019/182161534-46bdc6fd-e964-42fd-9d41-dc6d500f5413.png)

**Comment by zhicheng-ning** [comment]
Hi, @longyanz，有空可以看一下~

**Comment by longyanz** [comment]
如果将传入地址改成 http://localhost:8080/hello/hello-feign 是否会有返回值？抱歉我现在无法在自己的电脑上进行验证。

**Comment by Bruce-Jay** [comment]
> 如果将传入地址改成 http://localhost:8080/hello/hello-feign 是否会有返回值？抱歉我现在无法在自己的电脑上进行验证。

可以了，有返回值的！

**Comment by zhicheng-ning** [comment]
Thansk for @longyanz , @Bruce-Jay ~
