### ISSUE TITLE
本课程时间安排 & 课程腾讯会议号

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/DesignThinking-LeanStartup#3]
![image](https://user-images.githubusercontent.com/15010826/175814589-d2061ead-8f12-406a-a7a9-6dba31673665.png)

周一到周五，每天早上 9: 50 ~ 11: 25
从 6 月 27 日 ~ 7 月 22 日

然后发到微信群里提醒大家~

**Comment by zhicheng-ning** [comment]
宁志成 邀请您参加腾讯会议
会议主题：设计思维课程
会议时间：2022/06/27 09:30-11:30 (GMT+08:00) 中国标准时间 - 北京
重复周期：2022/06/27-2022/07/22 09:30-11:30, 每周 (工作日)

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/RRduERHMySlq

#腾讯会议：529-7055-5395

复制该信息，打开手机腾讯会议即可参与
