### ISSUE TITLE
设计6月30日的GitHub实践课内容

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/DesignThinking-LeanStartup#4]
当天助教上课：
- @tyn1998
- @zhicheng-ning

**Comment by tyn1998** [comment]
# 头脑风暴一下

## 痛点篇
- command/ctrl + Z Z Z Z Z Z Z Z……“靠，回不去了。。”（请用Git）
- “你用QQ传过代码吗？”大作业、大作业(1)、大作业最新、大作业最新(1)、大作业最新(1)(1)……（请用GitHub）
- 上划、上划、上划，怎么还没找到这条消息？No!!!新消息又把我翻了半天的聊天记录滚到最新消息去了！（请用GitHub）


## Git篇
- 哪些功能是Git的，哪些功能是GitHub的？要分清楚。
- .git这个目录包含了所有的东西。
- Git的三个区
- .gitignore
- Git的分布式特征，没有中心仓库/主仓库的说法。
- Git是如何判断冲突的？Git Merge的三路合并算法（分布式里，时间是不可靠的，才不是谁先提交就用谁的）。
- Git的每一个commit拿出来都能复原一个完整的项目目录，commit的内容不是增量，patch和diff才是。（[Git Objects](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects)）
- Git的分支只是一个指针，成本非常得低，开分支不要犹豫（删分支也一样）。“留得commit在，不怕没柴烧。”
- 你手头正在改代码，但是临时需要验证一个想法——请用git stash代替“复制粘贴先存个副本”。
- 在线可视化学习Git（https://learngitbranching.js.org/?locale=en_US）

## GitHub篇
- 首先它是一个remote的Git仓库，其他GitHub的特有功能让它成为了一个协作平台。（upstream、origin、local）
- 认真阅读README
- issues、PR、Discussions共享一个编号池；关闭Issue关闭/撤回PR不会让编号-1，编号单调递增。这意味着，你永远可以信任编号，尽量多引用它吧！
- 有问题，开issue；有需求，开issue；记事情，开issue。先开issue再做事！
  - 例子1
  - 例子2
  - 例子3
- PR = Git分支 + 评论/review
- PR不用非得等到事情做完了再提，早点提个draft PR上来，大家都能给意见。因为PR是一个Git分支，所以完全可以每完成一小部分就push一个commit到这个分支里来。
  - 例子1
  - 例子2
  - 例子3
- 现场演示：contributor是如何贡献代码的？
  - CONTRIBUTING流程
  - PR comments好复杂啊，怎么看懂时间线？怎么还有机器人？
  - 怎么有东西在跑？GitHub Actions。
- 现场演示：maintainer是如何review代码的？
  - 一切从收到了一封邮件说起
  - 看一下description
  - review界面
  - Merge按钮的三个选项
  - PR真好啊！所以，就算是自己的仓库，也不要直推，用PR，不要直推，用PR！
- 社交礼仪，大家要客客气气的。

**Comment by will-ww** [comment]
30 号的课，我可以把新一届的同学也拉过来听听，后面也一起在 GitHub 上和我们协作~

**Comment by AliceCodeZhang** [comment]
可以先摸摸同学们对git github已有的掌握能力，如果零基础，上面内容可能一节课给同学们说完有点压力 ：）

**Comment by tyn1998** [comment]
> 可以先摸摸同学们对git github已有的掌握能力，如果零基础，上面内容可能一节课给同学们说完有点压力 ：）

哈哈，谢谢张老师的建议！上面只是一个头脑风暴，之后肯定是选讲的。也是小小实践一下这门课的“先发散，再收敛”思维过程~

**Comment by AliceCodeZhang** [comment]
> > 可以先摸摸同学们对git github已有的掌握能力，如果零基础，上面内容可能一节课给同学们说完有点压力 ：）
> 
> 哈哈，谢谢张老师的建议！上面只是一个头脑风暴，之后肯定是选讲的。也是小小实践一下这门课的“先发散，再收敛”思维过程~

开始实践双钻模型了

**Comment by zhicheng-ning** [comment]
这边我贴一个当时学习 Git 的一个实践笔记供参考~
https://www.yuque.com/docs/share/5637517f-faae-4a12-bd29-cd5d332d6a3f?# 《Git 学习笔记》
目录结构：
- 下载 Git
- Git 配置文件
- 初始化本地库
- 查看本地库状态
- 添加暂存区
- 提交本地库
- 历史版本
  - 查看历史版本
  - 版本穿梭
- 分支操作
  - 创建分支
  - 查看分支
  - 切换分支
  - 合并分支
  - 产生冲突
  - 解决冲突
- Git 团队协作机制
  - 团队内协作
  - 跨团队协作
- 远程仓库操作
  - 创建远程仓库别名
  - 推送本地仓库到远程仓库
  - 拉取远程库代码到本地
  - 克隆远程仓库到本地
- 团队内协作（邀请加入团队）
- 跨团队协作
- SSH 免密登录
- IDEA 集成 Git 
- IDEA 集成 GitHub
- 推荐资料

**Comment by tyn1998** [comment]
Hi，大家好。我做了一个图，展示了一个比较通用的CONTRIBUTING过程：

<img width="596" alt="image" src="https://user-images.githubusercontent.com/32434520/176448498-8d76e191-9282-4734-89cd-5f0d0a750d1c.png">

不过暂时没有包含reviewer要求修改代码，然后contributor修改代码后再push的过程。

**Comment by tyn1998** [comment]
今天的课已经结束啦，谢谢大家，谢谢 @Bruce-Jay 的踊跃演示~
