### ISSUE TITLE
课程录制视频相关问题

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/DesignThinking-LeanStartup#5]
欢迎大家来讨论以下问题~

- Q1：课程录制的视频存放位置
- Q2：公开视频链接 or 私密发送

对于 Q1，目前想到的方式但不限于：
- 视频文件存放至 X-lab 实验室的B站账号，提供视频合集链接
- 存放至语雀资源库，提供公开链接
- 存放至 OSS，提供每次的视频链接

对于 Q2，目前想到的方式但不限于：
- 每次录制的课程视频，将其链接更新在 DesignThinking-LearnStartup 仓库的 README 文件中
- 助教每次将录制的视频链接私发至教学微信群

**Comment by tyn1998** [comment]
如果可以的话，我觉得B站最好了~

（语雀空间容量告急）

**Comment by zhicheng-ning** [comment]
@will-ww @AliceCodeZhang @chunchill  @tyn1998

**Comment by AliceCodeZhang** [comment]
如果课程会在水杉上建立课程，建议直接放在水杉课程里面，把所有PPT、视频 存放成一个一个课程周资源，同时设置分组作业，这样学生方便查看，老师收发作业也比较方便

**Comment by Bruce-Jay** [comment]
同意放在水杉上面，以课程为单位，视频也附上课件与作业，避免微信群中资源过期，或者消息接收不及时等等，实现微信通知与学习任务布置的分离。B站账号我觉得在水杉平台上传视频的同时也可以上传视频，因为水杉平台视频的体验并不是太好，包括暂停视频、拖动进度条等方面。

**Comment by AliceCodeZhang** [comment]
> 视频

B站视频直接作为水杉外链，这样都能兼顾

**Comment by tyn1998** [comment]
最后方案为在水杉平台开了[此门课](https://shuishan.net.cn/education/course/1542014615012753410)，视频都上传到水杉中。

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/32434520/176814785-a07d0bc4-8f50-45fd-b9ce-5cda6eaf15db.png">
