### ISSUE TITLE
【小记】同学们参加这门课的一些想法

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/DesignThinking-LeanStartup#6]
- 郭同学：怎么做一个实际作品，怎么发现自己的想法
- 许同学：这门课和其他专业课不大一样，想了解一下这门课
- 徐同学：
- 刘同学：希望能通过这门课做一个真正有用的东西；去年暑假有想选，但是被难度劝退了hh
- 刘同学：我想接触一下真正在实际应用中可以发挥作用的东西，开阔视野，偏应用偏工程的
- 徐同学：之前和学长学姐做创新创业项目，一直没有可以开发的点子，通过这门课学习优秀的项目
- 林同学：之前参加过开发项目，对开发有兴趣，选这门课希望从日常生活中得到启发，找到idea
- 张同学：
- 杨同学：

**Comment by liyunxi-ux** [comment]
杨同学表示，从来没有接触过这门课。。。属实有点不知所措了，顺便说一下，同学们都好厉害啊
