### ISSUE TITLE
【作业】23 个实验

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/DesignThinking-LeanStartup#8]
# 说明

- 因为实验材料还未出版，涉及版权问题，所以实验材料已经发在微信课程群中。
- 一共有 23 个实验，每个实验教程都是比较详细的，对于每一个实验，大家只需要按部就班实践一遍，然后把实验过程中的图片换成自己实践时的截图即可，可以每个实验最后写一两句自己的收获。
- **2022/08/14 更新：经过教学组商议，考虑到实验内容比较多，涉及到的技术面也很广，前端、后端、测试、DevOps 各方面都有。为了减轻同学们的负担，特此更新实验要求**
  - 完成至实验 8.1.8 ，给予实验及格分
  - 完成至实验 8.3.5 ，给予实验分满分
  - 截止日期延期至 2022/09/01

# 提交

请前往[水杉](https://www.shuishan.net.cn/education/course/1542014615012753410)“Lesson10 作业提交”提交一份PDF文件。

# 要求

> 请问报告里需要粘贴上实验材料的文字说明吗

按照自己的实践过程，用自己的话讲清楚就可以，如果能发现实验步骤或者内容有任何错误，欢迎提 Issue 或者联系助教！

> 有格式要求吗？

格式就是按照每个实验自己的格式【实验目的】【实验环境】【实验步骤】......，只要考虑目录层级就好了，字体什么的格式没有硬性规定。

_——摘自 #10_。

# 反馈

大家在实验过程中如果遇到和**实验内容本身**相关的问题，请一定要前往

https://github.com/OpenEduTech/DaseDevOps/issues

提issue，每个实验的负责同学会为大家解决~

# 截止日期

2022/09/01

**Comment by tyn1998** [comment]
已知问题（打勾则已解决）：

- [x] #9 
- [x] #11 
- [x] #12 
- [x] #15 
- [x] #24 
- [x] #25 
- [x] #26 
- [x] #27 
- [x] #28 
- [ ] https://github.com/OpenEduTech/DaseDevOps/issues/2

**Comment by Bruce-Jay** [comment]
请问实验如何提交呢

**Comment by zhicheng-ning** [comment]
> 请问实验如何提交呢

后面我们会在水杉课程中开放一个实验作业，大家将 23 个实验的内容写到一个文件里，最后只要上传一份 PDF 实验报告即可
